services:
  api:
    container_name: telegraph_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=pass
      - PGDATABASE=telegraph_dev
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: telegraph_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=telegraph_dev
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=pass
volumes:
  dbdata:
networks: 
  default:
    name: telegraph_app_dev